export const posts = [
    {
        id: 1,
        title: "Taj Mahal",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Taj_Mahal_in_India_-_Kristian_Bertel.jpg/375px-Taj_Mahal_in_India_-_Kristian_Bertel.jpg",
        alt: "Taj Mahal",
        desc: "The Taj Mahal was commissioned by Shah Jahan in 1631, to be built in the memory of his wife Mumtaz Mahal, who died on 17 June that year, while giving birth to their 14th child, Gauhara Begum.[12][13] Construction started in 1632,[14] and the mausoleum was completed in 1648, while the surrounding buildings and garden were finished five years later.[15] The imperial court documenting Shah Jahan's grief after the death of Mumtaz Mahal illustrates the love story held as the inspiration for the Taj Mahal.",
        longDesc: "The Taj Mahal incorporates and expands on design traditions of Indo-Islamic and earlier Mughal architecture. Specific inspiration came from successful Timurid and Mughal buildings including the Gur-e Amir (the tomb of Timur, progenitor of the Mughal dynasty, in Samarkand),[17] Humayun's Tomb which inspired the Charbagh gardens and hasht-behesht (architecture) plan of the site, Itmad-Ud-Daulah's Tomb (sometimes called the Baby Taj), and Shah Jahan's own Jama Masjid in Delhi. While earlier Mughal buildings were primarily constructed of red sandstone, Shah Jahan promoted the use of white marble inlaid with semi-precious stones. Buildings under his patronage reached new levels of refinement.The exterior decorations of the Taj Mahal are among the finest in Mughal architecture. As the surface area changes, the decorations are refined proportionally. The decorative elements were created by applying paint, stucco, stone inlays or carvings. In line with the Islamic prohibition against the use of anthropomorphic forms, the decorative elements can be grouped into either calligraphy, abstract forms or vegetative motifs. Throughout the complex are passages from the Qur'an that comprise some of the decorative elements. Recent scholarship suggests that Amanat Khan chose the passages.The calligraphy on the Great Gate reads O Soul, thou art at rest. Return to the Lord at peace with Him, and He at peace with you. The calligraphy was created in 1609 by a calligrapher named Abdul Haq. Shah Jahan conferred the title of Amanat Khan upon him as a reward for his dazzling virtuosity.[29] Near the lines from the Quran at the base of the interior dome is the inscription, Written by the insignificant being, Amanat Khan Shirazi. Much of the calligraphy is composed of florid thuluth script made of jasper or black marble[29] inlaid in white marble panels. Higher panels are written in slightly larger script to reduce the skewing effect when viewed from below. The calligraphy found on the marble cenotaphs in the tomb is particularly detailed and delicate",

    },
    {
        id: 2,
        title: "Great Wall of China",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/1280px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
        alt: "Great Wall of China",
        desc: "The Great Wall of China is a series of fortifications that were built across the historical northern borders of ancient Chinese states and Imperial China as protection against various nomadic groups from the Eurasian Steppe. ",
        longDesc: "The Chinese were already familiar with the techniques of wall-building by the time of the Spring and Autumn period between the 8th and 5th centuries BC.[22] During this time and the subsequent Warring States period, the states of Qin, Wei, Zhao, Qi, Han, Yan, and Zhongshan[23][24] all constructed extensive fortifications to defend their own borders. Built to withstand the attack of small arms such as swords and spears, these walls were made mostly of stone or by stamping earth and gravel between board frames.The Great Wall of the Han is the longest of all walls, from Mamitu near Yumenguan to Liaodong King Zheng of Qin conquered the last of his opponents and unified China as the First Emperor of the Qin dynasty (Qin Shi Huang) in 221 BC. Intending to impose centralized rule and prevent the resurgence of feudal lords, he ordered the destruction of the sections of the walls that divided his empire among the former states. To position the empire against the Xiongnu people from the north, however, he ordered the building of new walls to connect the remaining fortifications along the empire s northern frontier. Build and move on was a central guiding principle in constructing the wall, implying that the Chinese were not erecting a permanently fixed border.[25]Transporting the large quantity of materials required for construction was difficult, so builders always tried to use local resources. Stones from the mountains were used over mountain ranges, while rammed earth was used for construction in the plains. There are no surviving historical records indicating the exact length and course of the Qin walls. Most of the ancient walls have eroded away over the centuries, and very few sections remain today. The human cost of the construction is unknown, but it has been estimated by some authors that hundreds of thousands[26] workers died building the Qin wall. Later, the Han,[27] the Northern dynasties and the Sui all repaired, rebuilt, or expanded sections of the Great Wall at great cost to defend themselves against northern invaders.[28] The Tang and Song dynasties did not undertake any significant effort in the region.[28] Dynasties founded by non-Han ethnic groups also built their border walls: the Xianbei-ruled Northern Wei, the Khitan-ruled Liao, Jurchen-led Jin and the Tangut-established Western Xia, who ruled vast territories over Northern China throughout centuries, all constructed defensive walls but those were located much to the north of the other Great Walls as we know it, within China s autonomous region of Inner Mongolia and in modern-day Mongolia itself."
    },
    {
        id: 3,
        title: "Egyptian pyramids",
        img: "https://media.istockphoto.com/id/1142873955/photo/the-pyramids-of-giza-and-the-great-sphinx-egypt.jpg?s=612x612&w=0&k=20&c=WSyhLyJdMk21hWMp4plIxSvcDH2EFCKw6nIzQ5i1tQA=",
        alt: "Egyptian pyramids",
        desc: "The Egyptian pyramids are ancient masonry structures located in Egypt. Sources cite at least 118 identified Egyptian pyramids.[1][2] Approximately 80 pyramids were built within the Kingdom of Kush, now located in the modern country of Sudan. Of those located in modern Egypt, most were built as tombs for the country s pharaohs and their consorts during the Old and Middle Kingdom periods.",
        longDesc: "The design of Egyptian pyramids, especially the stepped designs of the oldest pyramids (Pyramid of Zoser at Saqqara, 2600 BCE), may have been an evolution from the ziggurats built in Mesopotamia, dated to as early as 4000–3500 BCE.[11][12] Preceded by assumed earlier sites in the Eastern Sahara, tumuli with megalithic monuments developed as early as 4700 BCE in the Saharan region of Niger.[13] It is also possible that these megalithic monuments in the Saharan region of Niger and the Eastern Sahara may have served as antecedents for the mastabas and pyramids of ancient Egypt.[13] During Predynastic Egypt, tumuli were present at various locations (e.g., Naqada, Helwan).[13] From the time of the Early Dynastic Period (c. 3150–2686 BCE), Egyptians with sufficient means were buried in bench-like structures known as mastabas.[14][15] At Saqqara, Mastaba 3808, dating from the latter part of the 1st Dynasty, was discovered to contain a large, independently built step-pyramid-like structure enclosed within the outer palace facade mastaba. Archaeological remains and inscriptions suggest there may have been other similar structures dating to this period.[16]The first historically documented Egyptian pyramid is attributed by Egyptologists to the 3rd Dynasty pharaoh Djoser. Although Egyptologists often credit his vizier Imhotep as its architect, the dynastic Egyptians themselves, contemporaneously or in numerous later dynastic writings about the character, did not credit him with either designing Djoser's pyramid or the invention of stone architecture.[17] The Pyramid of Djoser was first built as a square mastaba-like structure, which as a rule were known to otherwise be rectangular, and was expanded several times by way of a series of accretion layers, to produce the stepped pyramid structure we see today.[18] Egyptologists believe this design served as a gigantic stairway by which the soul of the deceased pharaoh could ascend to the heavens"
    },
    {
        id: 4,
        title: "Byzantine Church (Petra)",
        img: "https://media.istockphoto.com/id/637117156/photo/stunning-view-of-petra-church-unesco-heritage-in-rock.jpg?s=612x612&w=is&k=20&c=11UKqdPsIVVwWJbuOk5MMCpUTrsNHF0fwjEiL8wEWos=",
        alt: "Byzantine Church (Petra)",
        desc: "The Byzantine Church at Petra (also known as The Petra Church) is a prime example of monumental architecture in Byzantine Petra. It sits on elevated ground in the city center, north of the so-called Colonnaded Street.[1][2] It is one of three Byzantine churches on the hillside, the others two being the Ridge Church (or Red Church)[3] and the Blue Chapel, the 5th - 6th century chapel north of the main church, so called because it was fashioned with blue Egyptian granite.",
        longDesc: "Archaeologists have concluded that the Church was originally built in the second half of the fifth century CE. It continued to be used as a religious structure until about the early seventh century CE, when it was destroyed by fire.[2]Zbigniew Fiema notes that scholars distinguish “early” and “late” phases of construction. The early phase designates the church as originally built in the fifth century CE. The late phase corresponds to modifications carried out in the later sixth century CE.[2]In the sixth century, the atrium of the church was built to connect the cathedral portion of the church to the baptismal complex, joining them into one building.[1] After the fire, materials from the Church were reused, including the glass tesserae (small cubes that make up mosaics) from the mosaicsThe Church includes a baptismal complex, an atrium (or foyer space), and a cathedral.[1] Inside the cathedral section, the “bema” or altar sits at one end of the nave on a raised platform that sits before three apses.  The largest of these apses is the one in the center, where a cathedra, or bishop's throne, once sat.[2] It is likely that wooden benches would have been attached to the walls of the Church.[2]The walls of the church are made of ashlar masonry. The chisel marks that are visible in the masonry are similar to those that appear in earlier Nabataean architecture, and indicate a continuity in masonry practices. The architecture of the Church includes Nabataean rock-chiseled elements and Roman and Hellenistic mosaic styles. The variety of architectural forms present at the Byzantine Church are part of a larger conversation on hybridism, a term in archaeology used when multiple cultural styles are present in one object or structure."
    },
    {
        id: 5,
        title: "Machu Picchu",
        img: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8bWFjaHUlMjBwaWNjaHV8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
        alt: "Machu Picchu",
        desc: "Machu Picchu is a 15th-century Inca citadel located in the Eastern Cordillera of southern Peru on a 2,430-meter (7,970 ft) mountain range.[2][3] It is located in the Machupicchu District within Urubamba Province[4] above the Sacred Valley, which is 80 kilometers (50 mi) northwest of Cusco. The Urubamba River flows past it, cutting through the Cordillera and creating a canyon with a tropical mountain climate",
        longDesc: "Machu Picchu was believed (by Richard L. Burger, professor of anthropology at Yale University) to have been built in the 1450s.[23] However, a 2021 study led by Burger used radiocarbon dating (specifically, AMS) to reveal that Machu Picchu may have been occupied from around 1420–1530 AD.[24][25] Construction appears to date from two great Inca rulers, Pachacutec Inca Yupanqui (1438–1471) and Túpac Inca Yupanqui (1472–1493).[26][27]: xxxvi  There is a consensus among archaeologists that Pachacutec ordered the construction of the royal estate for his use as a retreat, most likely after a successful military campaign. Although Machu Picchu is considered to be a royal estate, it would not have been passed down in the line of succession. Rather it was used for 80 years before being abandoned, seemingly because of the Spanish conquests in other parts of the Inca Empire.[23] It is possible that most of its inhabitants died from smallpox introduced by travelers before the Spanish conquistadors arrived in the area During its use as a royal estate, it is estimated that about 750 people lived there, with most serving as support staff (yanaconas, yana)[29][page needed][30] who lived there permanently. Though the estate belonged to Pachacutec, religious specialists and temporary specialized workers (mayocs) lived there as well, most likely for the ruler's well-being and enjoyment. During the harsher season, staff dropped down to around a hundred servants and a few religious specialists focused on maintenance alone.[29][page needed] Studies show that, according to their skeletal remains, most people who lived there were immigrants from diverse backgrounds. They lacked the chemical markers and osteological markers they would have if they had been living there their whole lives. Instead, there was bone damage from various species of water parasites indigenous to different areas of Peru. There were also varying osteological stressors and varying chemical densities suggesting varying long-term diets characteristic of specific regions that were spaced apart.[31] These diets are composed of varying levels of maize, potatoes, grains, legumes, and fish, but the overall most recent short-term diet for these people was composed of less fish and more corn. This suggests that several of the immigrants were from more coastal areas and moved to Machu Picchu where corn was a larger portion of food intake.[30] Most skeletal remains found at the site had lower levels of arthritis and bone fractures than those found in most sites of the Inca Empire. Inca individuals who had arthritis and bone fractures were typically those who performed heavy physical labor (such as the Mit'a) or served in the Inca military."
    },
    {
        id: 6,
        title: "Kukulkan (Chichen Itza)",
        img: "https://media.istockphoto.com/id/481309071/photo/el-castillo-of-chichen-itza-at-sunset-mexico.jpg?s=612x612&w=0&k=20&c=9m_KO5HfjltIN5K48uOvfazZZYulITWtMF7MkBTu5Ow=",
        alt: "Kukulkan Temple(Chichen Itza)",
        desc: "El templo, known as the Temple of Kukulcán (or also just as Kukulcán), is a Mesoamerican step-pyramid that dominates the center of the Chichen Itza archaeological site in the Mexican state of Yucatán. The temple building is more formally designated by archaeologists as Chichen Itza Structure 5B18",
        longDesc: "The construction of Kukulcán (El Templo), like other Mesoamerican temples, likely reflected the common practice by the Maya of executing several phases of construction for their temples. The last construction probably took place between 900–1000 AD, while the substructure may have been constructed earlier, between 600–800 AD. Based on archaeological research, construction of Kukulcán was based on the concept of axis mundi.[5] Anthropologists think that the site remained sacred regardless of how the structure was positioned on the location. When a temple structure was renewed, the former construction was destroyed using a ritual that involved resolving the space of spiritual forces to preserve its sacredness.[6] It is estimated that this last construction dates to the eleventh century AD. The older, inner temple is referred to as the substructure.After all of the restoration work was completed, an entryway was cut into the balustrade of the northeastern exterior staircase to provide access to tourists. In 1566, the temple was described by Friar Diego de Landa in the manuscript known as Yucatán at the Time of the Spanish Encounter (Relación de las cosas de Yucatán). Almost three centuries later, John Lloyd Stephens described the architecture of the temple with even more detail in his book Incidents of Travel in Yucatán (Incidentes del viaje Yucatán), published in 1843. At that time, the archaeological site of Chichén Itzá was located on an estate, also called Chichén Itzá, owned by Juan Sosa. Frederick Catherwood illustrated the book with lithographs depicting the temple covered in abundant vegetation on all sides. There are some photographs taken in the beginning of the twentieth century that also show the temple partially covered by said vegetation.In 1924, the Carnegie Institution for Science in Washington, D.C. requested permission from the Mexican government to carry out explorations and restoration efforts in and around the area of Chichen Itza. In 1927, with the assistance of Mexican archaeologists, they started the task. In April 1931, looking to confirm the hypothesis that the structure of the temple of Kukulcán was built on top of a much older temple, the work of excavation and exploration began in spite of generalized beliefs contrary to that hypothesis. On June 7, 1932, a box with coral, obsidian, and turquoise encrusted objects was found alongside human remains, which are exhibited in the National Anthropology Museum in Mexico City."
    },
    {
        id: 7,
        title: "Parthenon",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/450px-The_Parthenon_in_Athens.jpg",
        alt: "Parthenon",
        desc: "The Parthenon  is a former temple on the Athenian Acropolis, Greece, that was dedicated to the goddess Athena during the fifth century BC. Its decorative sculptures are considered some of the high points of Greek art, an enduring symbol of Ancient Greece, democracy and Western civilization.",
        longDesc: "The origin of the word Parthenon comes from the Greek word parthénos (παρθένος), meaning maiden, girl as well as virgin, unmarried woman. The Liddell–Scott–Jones Greek–English Lexicon states that it may have referred to the unmarried women's apartments in a house, but that in the Parthenon it seems to have been used for a particular room of the temple.[17] There is some debate as to which room that was. The lexicon states that this room was the western cella of the Parthenon. This has also been suggested by J.B. Bury.[10] Jamauri D. Green claims that the Parthenon was the room where the arrephoroi, a group of four young girls chosen to serve Athena each year, wove a peplos that was presented to Athena during Panathenaic Festivals.[18] Christopher Pelling asserts that the name Parthenon means the temple of the virgin goddess, referring to the cult of Athena Parthenos that was associated with the temple.[19] It has also been suggested that the name of the temple alludes to the maidens (parthénoi), whose supreme sacrifice guaranteed the safety of the city.[20] In that case, the room originally known as the Parthenon could have been a part of the temple known today as the Erechtheion.[21]In 5th-century BC accounts of the building, the structure is simply called ὁ νᾱός (ho naos; lit. the temple). Douglas Frame writes that the name Parthenon was a nickname related to the statue of Athena Parthenos, and only appeared a century after construction. He contends that Athena s temple was never officially called the Parthenon and she herself most likely never had the cult title parthénos. The ancient architects Iktinos and Callicrates appear to have called the building Ἑκατόμπεδος (Hekatómpedos; lit. the hundred footer) in their lost treatise on Athenian architecture.[23] Harpocration wrote that some people used to call the Parthenon the Hekatompedos, not due to its size but because of its beauty and fine proportions.[23] The first instance in which Parthenon definitely refers to the entire building comes from the fourth century BC orator Demosthenes.[citation needed] In the 4th century BC and later, the building was referred to as the Hekatompedos or the Hekatompedon as well as the Parthenon. Plutarch referred to the building during the first century AD as the Hekatompedos Parthenon"
    },

];